server:
  port: 1099

spring:
  application:
    name: crypto-trading
  datasource:
    url: jdbc:h2:mem:crypto_trading;DB_CLOSE_DELAY=1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2

priceFetching:
  timeRateInMs: 10000
  binanceUrl: "https://api.binance.com/api/v3/ticker/bookTicker"
  huobiUrl: "https://api.huobi.pro/market/tickers"